name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        ##woworking-directory:Informa o diretoria que será executado a ação 
        run: echo "Hello World !!!"
      - name: "Segunda ação"
        run: |
          echo "Você criou o seu primeiro workflow!!"
          echo "Parabéns!!!"
      - name: "Script Python"
        run: |
          variavel = "Hello World!!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: [primeiro-job] 
    steps:
      - name: "Verificação da versão do Node JS Atual"
        run: node --version
      - name: "Definição node latest"
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: "Verificação da versão do Node JS Atual"
        run: node --version
    
